---
function:
  name: omni-wt-rt-shipment-header-trigger-${self:provider.stage}
  handler: src/fullLoad/index.shipmentHeaderBatchTrigger
  provisionedConcurrency: 1
  concurrencyAutoscaling: true
  layers:
    - { Ref: OmniRealTimeReplicationLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/fullLoad/index.js"
  events:
    - http:
        path: shipment-header
        method: post
        cors: true
