ShipmentAparTopic:
  Type: AWS::SNS::Topic
  Properties:
    TopicName: omni-wt-rt-shipment-apar-${self:provider.stage}

ToyotaShipmentAparSubscription:
  Type: AWS::SNS::Subscription
  Properties:
    TopicArn: !Ref ShipmentAparTopic
    Endpoint: !GetAtt
      - ToyotaTargetQueue
      - Arn
    Protocol: sqs
    RawMessageDelivery: "true"
