const confirmationCostTableMapping = [
    "PK_ConfirmationNo", // Partition Key
    "FK_OrderNo", // Sort Key
    "CarrierContact",
    "CarrierFax",
    "CarrierId",
    "CarrierName",
    "CarrierPhone",
    "ConAddress1",
    "ConAddress2",
    "ConCity",	
    "ConContact",
    "ConFax",
    "ConName",
    "ConPhone",
    "Consolidation",
    "ConsolNo",
    "ConZip",
    "DeliveryDateTime",
    "DeliveryNote",
    "DeliveryTimeRange",
    "DeliveryWeight",
    "Description",
    "DestAirport",
    "DMS_TS",
    "FK_ConCountry",
    "FK_ConState",
    "FK_SeqNo",
    "FK_ShipCountry",
    "FK_ShipState",	
    "InsertedTimeStamp",
    "IsDefault",	
    "MaxConsolWeight",
    "OrgAirport",
    "OverMaxConsolweight",
    "PickupDateTime",	
    "PickupNote",	
    "PickupTimeRange",	
    "PickupWeight",
    "Product",
    "SealNo",	
    "ShipAddress1",
    "ShipAddress2",	
    "ShipCity",
    "ShipContact",
    "ShipFax",
    "ShipName",
    "ShipPhone",
    "ShipZip",
    "TrailerNo",
    "transact_id",

];

module.exports = confirmationCostTableMapping