const consolStopHeadersTableMapping = [
    "PK_ConsolStopId", // Partition Key
    "ConsolDeliveryAgent",
    "ConsolPreventStatusUpdates",
    "ConsolStopAddress1",
    "ConsolStopAddress2",
    "ConsolStopArea",
    "ConsolStopCity",
    "ConsolStopContact",
    "ConsolStopCustomerVendorLookupData",
    "ConsolStopCustomerVendorLookupState",
    "ConsolStopDate",
    "ConsolStopEmail",
    "ConsolStopETADateTime",
    "ConsolStopFax",
    "ConsolStopName",
    "ConsolStopNotes",
    "ConsolStopNumber",
    "ConsolStopPhone",
    "ConsolStopPickupOrDelivery",
    "ConsolStopTimeBegin",
    "ConsolStopTimeEnd",
    "ConsolStopZip",
    "DMS_TS",
    "FK_ConsolNo",
    "FK_ConsolStopAirport",
    "FK_ConsolStopCountry",
    "FK_ConsolStopState",
    "InsertedTimeStamp",
    "transact_id",
];

module.exports = consolStopHeadersTableMapping;