const shipmentHeaderTableMapping = [
  "PK_OrderNo", // - {Primary Key}
  "UserId",
  "BillNo",
  "OrgAirport",
  "DestAirport",
  "FK_OrderStatusId",
  "MasterAirWaybill",
  "HandlingStation",
  "Housebill",
  "Insurance",
  "HazmatCode",
  "PODName",
  "PODDateTime",
  "PODDateTimeZone",
  "ReadyDateTime",
  "ReadyDateTimeZone",
  "ReadyDateTimeRange",
  "RcvdDateTime",
  "ScheduledDateTime",
  "ScheduledDateTimeZone",
  "OrderDate",
  "ScheduledDateTimeRange",
  "ScheduledBy",
  "ShipmentDateTime",
  "ShipmentDateTimeZone",
  "CloseTime",
  "AssignedInvNo",
  "FK_ServiceLevelId",
  "FK_Salesperson",
  "DateTimePosted",
  "PODDateTimeEntered",
  "Tariff",
  "TariffCode",
  "TotalMiles",
  "FK_ModeId",
  "FK_ControlCustomerNo",
  "ShipmentType",
  "FK_IncoTermCode",
  "FK_ContainerCode",
  "ShipQuote",
  "ControllingStation",
  "FK_InsuranceType",
  "FK_EquipmentCode",
  "LoadBoardID",
  "DestinationPort",
  "FK_ExemptionCode",
  "FK_FirmsCode",
  "FK_PLStatus",
  "FK_ProductCode",
  "FK_TractorCode",
  "ETADateTime",
  "ETADateTimeZone",
  "ReceivedDateTime",
  "DestArrivalDateTime",
  "FK_RegionCode",
  "FK_CategoryCode",
  "FK_ProjectCode",
  "FK_ReasonCode",
  "InsertedTimeStamp", // value manually manually
  "UUid", // value manually manually
  "ProcessState" // value manually manually
];

module.exports = shipmentHeaderTableMapping;
