const shipmentAparTableMapping = [
  "FK_OrderNo", // Partition Key
  "SeqNo", // Sort Key
  "FK_ServiceId",
  "Weight",
  "Override",
  "Rate",
  "Cost",
  "Extra",
  "Tax",
  "Description",
  "APARType",
  "Quantity",
  "ChargeCode",
  "Total",
  "APARCode",
  "FK_CodeNo",
  "RefNo",
  "FK_AirCode",
  "FK_ContainerCode",
  "Finalize",
  "FinalizedTotal",
  "FK_CustNo",
  "InvoiceSeqNo",
  "PKSeqNo",
  "InvoiceNo",
  "InvoiceDate",
  "DueDate",
  "ReadyForInvoice",
  "InvPrinted",
  "Consolidation",
  "ConsolNo",
  "InvPrintedDate",
  "FK_VendorId",
  "FinalizedDate",
  "VendorAmount",
  "CreateDateTime",
  "ConsolShipDateTime",
  "FK_ConsolStationId",
  "CustomerInvoiceNo",
  "Currency",
  "FK_HandlingStation",
  "FK_AccountCode",
  "UpdatedBy",
  "UpdatedOn",
  "FK_ConsolStatusId",
  "APARStatus",
  "Complete",
  "VendorCostSeqNo",
  "ReadyForInvoiceDateTime",
  "FinalizedBy",
  "FK_PaymentTermCode",
  "FK_PaymentTermCode1",
  "PostedDateTime",
  "FK_EquipmentCode",
  "InsertedTimeStamp", // value manually manually
];

module.exports = shipmentAparTableMapping;
