---
function:
  name: omni-wt-rt-consol-stop-headers-${self:provider.stage}
  handler: src/realtime/consolStopHeadersRt.handler
  memorySize: 1024
  timeout: 90
  
  layers:
    - { Ref: OmniRealTimeReplicationLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/realtime/consolStopHeadersRt.js"
      - "src/shared/**"
  environment:
    DYNAMO_DB_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consol-stop-headers/ddb.tableName~true}
  events:
    - sqs:
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consol-stop-headers/queue.arn~true}
        batchSize: 10
        functionResponseType: ReportBatchItemFailures