---
function:
  name: omni-dw-service-level-${self:provider.stage}
  handler: src/realtime/serviceLevelRt.handler
  memorySize: 1024
  timeout: 90

  layers:
    - { Ref: OmniRealTimeReplicationLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/realtime/serviceLevelRt.js"
      - "src/shared/**"
  environment:
    DYNAMO_DB_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/servicelevels/ddb.tableName~true} 
  # events:
  #   - sqs:
  #       arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/servicelevels/queue.arn~true} 
  #       batchSize: 10
  #       functionResponseType: ReportBatchItemFailures
  iamRoleStatementsName: omni-wt-rt-servicelevels-${self:provider.stage}-role 
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
