const customerTableMapping = [
    "PK_CustNo",// Partition Key
    "CustName",
    "CustAddress1",
    "CustAddress2",
    "CustCity",
    "FK_CustState",
    "CustZip",
    "FK_CustCountry",
    "CustPhone",
    "DateTimeCustCreated",
    "FK_UserID",
    "InternetAddress",
    "Email",
    "FK_Salesperson",
    "Terms",
    "FK_CurrencyId",
    "Active",
    "CreditLimit",
    "CreditHold",
    "DefaultRefNo",
    "DefaultRefType",
    "FK_ControllingCustNo",
    "FK_StationId",
    "CustomerId",
    "CustomerHB",
    "FK_VendorNo",
    "FK_AirportId",
    "Area",
    "Miles",
    "FK_CtrlStationId",
    "InsertedTimeStamp",// value manually manually
];

module.exports = customerTableMapping;